### ISSUE TITLE
Make validataclasses dual-usable

### ISSUE THREAD

**Issue by the-infinity** [binary-butterfly/validataclass#9]
In some situations dataclass definitions can be used internally without validation and as an validation of external data. For example you can use an item for internal data constructions

```
@dataclass
CartItem:
  value: Decimal
  name: str = 'shopping item'
  description: Union[str, UnsetValueType] = UnsetValue
```
If the same model is used for incoming data, a validataclass would look like this:

```
@validataclass
CartItemInput:
  value: Decimal = DecimalValidator()
  name: str = StringValidator(), Default('shopping_item')
  description: Union[str, UnsetValueType] = StringValidator(), DefaultUnset()
```

If we want to re-use `CartItemInput` because `CartItemInput` is basicly the same, this is just possible if you pass all parameters to `CartItemInput`, otherwise `__init__` will complain about missing values:

```
cart_item_1 = CartItemInput(value=Decimal('1'), name='cookie', description='nom nom) # works
cart_item_2 = CartItemInput(value=Decimal('1'))  # does not work because default values are missing
cart_item_3 = CartItem(value=Decimal('1'))  # works, name and decription use default values
```

But: all data including the default values is there, so it should be possible to extend dataclass' `__init__`  in order to re-use `CartItemInput` for internal use without validation, too.
